version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: '-'
    commit-message:
      # cause a release for non-dev-deps
      prefix: fix(deps)
      # no release for dev-deps
      prefix-development: chore(dev-deps)
