#!/usr/bin/expect -f

cd frax-governance
spawn ../bin/run preview script/test/DeployTestnet.s.sol --private-key "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6" --broadcast --chain-id 1
expect "Do you wish to continue?"
send "y"
expect eof
