name: Integration Tests 🌁

on:
  pull_request:
  push:
    branches:
      - main
  release:

jobs:
  forge-simple:
    name: Forge Simple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metal CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Forge Simple
        run: |
          git clone https://github.com/0xMetropolis/forge-simple.git
          cd forge-simple
          git checkout d38ea9337144c05d5abbdb36fc5badd76d38324c
          forge install

      - name: Run Metal CLI
        working-directory: forge-simple
        env:
          RPC_URL: http://127.0.0.1:8545
          NO_METAL_SERVICE: true
        run: |
          anvil --chain-id 1 &
          ../bin/run preview script/Deploy.s.sol --UNSAFE-RPC-OVERRIDE $RPC_URL --chain-id 1

  bulla-contracts-v2:
    name: Bulla Contracts V2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metal CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Bulla Contracts V2
        run: |
          git clone https://github.com/bulla-network/bulla-contracts-v2.git
          cd bulla-contracts-v2
          git checkout edfeb6a356fe48b3806da5d8fb1a7ab4d9a9258b
          yarn
          forge install

      - name: Run Metal CLI
        working-directory: bulla-contracts-v2
        env:
          FEE_RECEIVER: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
          LOCK_STATE: 0
          RPC_URL: http://127.0.0.1:8545
          PK: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
          NO_METAL_SERVICE: true
        run: |
          anvil --chain-id 1 &
          ../bin/run preview script/Deployment.s.sol --private-key $PK --UNSAFE-RPC-OVERRIDE $RPC_URL --chain-id 1

  frax-governance:
    name: Frax Governance 👩‍⚖️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metal CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Frax Governance
        run: |
          git clone https://github.com/FraxFinance/frax-governance.git
          cd frax-governance
          git checkout 776e70d4e48c3f6a84b353518a1b3af9b931237a
          npm i

      - name: Run Metal CLI
        working-directory: frax-governance
        env:
          RPC_URL: http://127.0.0.1:8545
          PK: '0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6'
          NO_METAL_SERVICE: true
        run: |
          anvil --chain-id 1 --code-size-limit 5000000 &
          ../bin/run preview script/test/DeployTestnet.s.sol --private-key $PK --code-size-limit 5000000 --UNSAFE-RPC-OVERRIDE $RPC_URL --chain-id 1

  llama:
    name: Llama 🦙
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metal CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Llama
        run: |
          git clone https://github.com/code-423n4/2023-06-llama.git
          cd 2023-06-llama
          git checkout 9d422c264b57657098c2784aa951852cad32e01c
          forge install
          forge build

      - name: Run Metal CLI
        working-directory: 2023-06-llama
        env:
          RPC_URL: http://127.0.0.1:8545
          PK: '0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6'
          NO_METAL_SERVICE: true
          ETHERSCAN_API_KEY: 'XFGE58C46F89RWGDW6EZ8SYFNGH22J70J6' # not real, but required by the script
        run: |
          anvil --chain-id 1 --code-size-limit 5000000 &
          ../bin/run preview script/DeployLlama.s.sol --private-key $PK --code-size-limit 5000000 --UNSAFE-RPC-OVERRIDE $RPC_URL --chain-id 1
