name: Integration Tests 🌁

on:
  pull_request:
  push:
    branches:
      - main
  release:

jobs:
  forge-simple:
    name: Forge Simple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metro CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Forge Simple
        run: |
          git clone https://github.com/0xMetropolis/forge-simple.git
          cd forge-simple
          forge install

      - name: Run Metro CLI
        working-directory: forge-simple
        env:
          RPC_URL: http://127.0.0.1:8545
          PK: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
        run: |
          anvil &
          ../bin/run preview script/Deploy.s.sol --broadcast --private-key $PK --rpc-url $RPC_URL

  bulla-contracts-v2:
    name: Bulla Contracts V2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metro CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Bulla Contracts V2
        run: |
          git clone https://github.com/bulla-network/bulla-contracts-v2.git
          cd bulla-contracts-v2
          git checkout 895d67f0cf4d32d63624d04ddeb03fcac4743236
          yarn
          forge install

      - name: Run Metro CLI
        working-directory: bulla-contracts-v2
        env:
          FEE_RECEIVER: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
          LOCK_STATE: 0
          RPC_URL: http://127.0.0.1:8545
          PK: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
        run: |
          anvil &
          ../bin/run preview script/Deployment.s.sol --broadcast --private-key $PK

  frax-governance:
    name: Frax Governance 👩‍⚖️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Metro CLI
        run: |
          yarn
          yarn build
          yarn install:global

      - name: Clone Frax Governance
        run: |
          git clone https://github.com/FraxFinance/frax-governance.git
          cd frax-governance
          git checkout 776e70d4e48c3f6a84b353518a1b3af9b931237a
          npm i

      - name: Run Metro CLI
        working-directory: frax-governance
        env:
          PK: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
        run: |
          anvil --code-size-limit 5000000 &
          echo 'y' | ../bin/run preview script/Deployment.s.sol --broadcast --private-key $PK 
